# Project 1 - Data Cleaning and Preparation

### Internship: DecodeLabs Data Analytics

**Objective:**
To clean and prepare the given e-commerce dataset by identifying missing values, checking duplicate records, verifying data formats, and preparing the dataset for analysis.

In [1]:
print("Welcome to Decode Labs Project 1")

Welcome to Decode Labs Project 1

## Step 1 - Import Required Library

In this step, the Pandas library is imported. Pandas is used for reading, cleaning, manipulating, and analyzing tabular data.

In [4]:
import pandas as pd

## Step 2 - Load the Dataset

The Excel dataset is loaded into a Pandas DataFrame named **df** for further analysis and cleaning.

In [5]:
df=pd.read_excel("Dataset/Dataset for Data Analytics.xlsx")

## Step 3 - Display the Dataset

The complete dataset is displayed to verify that it has been loaded successfully.

In [6]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

## Step 4 - View the First Five Records

The first five rows of the dataset are displayed to understand the structure and contents of the data.

In [7]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

## Step 5 - View the Last Five Records

The last five rows are displayed to ensure the dataset has been loaded completely.

In [8]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

## Step 6 - Check Dataset Dimensions

The number of rows and columns in the dataset is identified.

In [11]:
df.shape

(1200, 14)

## Step 7 - Display Column Names

The column names are displayed to understand the structure of the dataset.

In [12]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='str')

## Step 8 - Dataset Information

The data type, number of non-null values, and memory usage of each column are examined.

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

## Step 9 - Identify Missing Values

Missing values are checked in every column to determine whether any cleaning is required.

In [14]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

## Step 10 - Handle Missing Values

The missing values in the **CouponCode** column are replaced with **"NO_COUPON"** because customers may not have applied any coupon while placing their orders.

In [15]:
df["CouponCode"] = df["CouponCode"].fillna("NO_COUPON")

## Step 11 - Verify Missing Values

The dataset is checked again to ensure that all missing values have been handled successfully.

In [16]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

## Step 12 - Check for Duplicate Records

The dataset is checked to identify any duplicate rows.

In [17]:
df.duplicated().sum()

np.int64(0)

## Step 13 - Verify Duplicate Order IDs

The **OrderID** column is checked to ensure that every order has a unique identifier.

In [18]:
duplicates = df.duplicated(subset="OrderID").sum()
duplicates

np.int64(0)

## Step 14 - Verify Date Format

The Date column is inspected to ensure that all dates follow a consistent format.

In [19]:
df["Date"].head(10)

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
5   2023-10-23
6   2025-06-17
7   2023-05-12
8   2025-04-02
9   2023-11-21
Name: Date, dtype: datetime64[us]

## Step 15 - Check Date Data Type

The data type of the Date column is verified to confirm that it is stored as a datetime value.

In [20]:
df["Date"].dtype

dtype('<M8[us]')

## Step 16 - Verify Product Names

The Product column is inspected to check for any inconsistencies or unwanted spaces.

In [21]:


df["Product"].head(10)

0    Monitor
1      Phone
2     Tablet
3      Chair
4    Printer
5      Phone
6     Laptop
7    Monitor
8      Phone
9       Desk
Name: Product, dtype: str

## Step 17 - Remove Extra Spaces

The `str.strip()` function is applied to remove any leading or trailing spaces from the Product column.

In [22]:
df["Product"] = df["Product"].str.strip()

## Step 18 - Verify Product Names After Cleaning

The Product column is displayed again to confirm that the values are properly formatted.

In [23]:
df["Product"].head(10)

0    Monitor
1      Phone
2     Tablet
3      Chair
4    Printer
5      Phone
6     Laptop
7    Monitor
8      Phone
9       Desk
Name: Product, dtype: str

## Step 19 - Verify Unit Price Values

The UnitPrice column is checked to ensure that the numeric values are stored correctly.

In [24]:
df["UnitPrice"].head(10)

0    570.62
1    151.35
2    550.68
3    273.19
4    626.01
5    245.86
6    664.42
7    149.55
8    134.28
9    509.38
Name: UnitPrice, dtype: float64

## Step 20 - Verify Total Price Values

The TotalPrice column is checked to verify that the calculated prices are stored correctly.

In [25]:
df["TotalPrice"].head(10)

0    2853.10
1     302.70
2    2753.40
3     273.19
4    2504.04
5     491.72
6     664.42
7     747.75
8     268.56
9    2037.52
Name: TotalPrice, dtype: float64

## Step 21 - Statistical Summary

A statistical summary of the UnitPrice and TotalPrice columns is generated using the `describe()` function.

In [26]:
df[["UnitPrice", "TotalPrice"]].describe()

         UnitPrice   TotalPrice
count  1200.000000  1200.000000
mean    356.412750  1053.968300
std     197.177146   819.856558
min      11.390000    11.390000
25%     186.062500   410.520000
50%     364.210000   823.615000
75%     521.570000  1578.475000
max     699.930000  3456.400000

## Step 22 - Save the Cleaned Dataset

The cleaned dataset is exported to a new Excel file named **cleaned_dataset.xlsx**.

In [27]:
df.to_excel("cleaned_dataset.xlsx", index=False)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

In [29]:
df.to_excel("cleaned_dataset.xlsx", index=False)

# Project Summary

### Tasks Completed

- Imported the dataset successfully.
- Explored the dataset structure.
- Identified missing values.
- Replaced missing CouponCode values with **NO_COUPON**.
- Verified that no missing values remain.
- Checked for duplicate records and duplicate Order IDs.
- Verified date formats and data types.
- Checked and standardized text data.
- Verified numeric columns.
- Exported the cleaned dataset successfully.

**Result:** The dataset has been cleaned, validated, and is ready for further data analysis.